### ISSUE TITLE
Assigning to attributes seems to work

### ISSUE THREAD

**Issue by akaIDIOT** [NetherlandsForensicInstitute/confidence#26]
~~~~ python
config.namespace.key = 'value'
~~~~

Does not raise an error and sometimes / often even seems to work. When `namespace` is available, this is sort of harmless, but when it isn't, `key = 'value'` gets assigned to `NotConfigured`, which has nasty side effects.

Assignments to `Configuration` objects should raise a clear error (`ValueError('assignment not supported')` or something) and documentation should clearly state this won't work and why. Merging a `Configuration` with a `dict` would enable 'write support' from code, this use case should be clearly documented (#22).

**Comment by bartbroere** [comment]
It seemed a bit off-topic to put in the review of PR 27, but what do you think confidence should do with the following type of "collisions"?
```
>>> config = confidence.Configuration({'keys': 'value', '_separator': 'l'})
>>> config.keys
<bound method Mapping.keys of <confidence.Configuration object at 0x7f4a48b0b898>>
>>> config.get('keys')
'value'
```
Should it show a warning if it is initialized with mappings with keys that would also show up in a call to ``dir(config)``? Unsuspecting users might use keys such as ``keys`` or ``items`` in their configuration files.
