### ISSUE TITLE
Enum values should be upper case

### ISSUE THREAD

**Issue by akaIDIOT** [NetherlandsForensicInstitute/confidence#67]
Definitions stem from a time when all the examples in the `enum` module in the Python stdlib were lower case, this has since been changed to align with enums in other languages. `confidence` should follow the documentation in the stdlib, though that might break user code; maybe deprecate the lower case variants and duplicate them upper cased?

**Comment by drxzcl** [comment]
Deprecation doesn’t do much. You give users a grace period that they either use (in which case you don’t gain anything wrt breaking changes) or don’t use (so they have to scramble to fix when the deprecation period ends, same as they would in the case of breaking changes). But it costs the maintainers twice the work. 

I vote for break and document. Holdouts can give themselves a deprecation period using version pinning.

**Comment by akaIDIOT** [comment]
Fair enough, let's YOLO them enums :)

**Comment by akaIDIOT** [comment]
Came across [a rationale from The Man™](https://mail.python.org/pipermail/python-ideas/2016-September/042340.html). If our lord and saviour would recommend uppercased enum values, than let's go with that :)
