### ISSUE TITLE
confidence.dumps() assumes the argument will be a confidence object

### ISSUE THREAD

**Issue by akaIDIOT** [NetherlandsForensicInstitute/confidence#98]
This assumption causes errors when users try to dump subtrees or values. While dump was envisioned to be for confidence objects, there's no good reason why calling `confidence.dumps(config.foo.bar)` shouldn't work.

**Comment by HHoofs** [comment]
Deze is done toch?

**Comment by akaIDIOT** [comment]
Whoops, true, thnx.
